### PR TITLE
WIP: Add arm images to docker builds to allow RPI's to host api

### PR DESCRIPTION
**Pull request by broodroosterdev**
By cross-building with buildx for arm, people can host the api on RPI without compiling it themselves. I have so far tested everything except publishing to docker hub.

### CODE REVIEW

**Comment by broodroosterdev** [comment]
Would you mind testing the publishing to docker hub @ATechnoHazard ?

**Comment by broodroosterdev** [comment]
I have tested building to Docker Hub and it works as expected. I will now test the image on my own rpi and if that is succesful, it is ready to be merged imo.

**Comment by SphericalKat** [comment]
Sounds good to me, lmk what happens.

**Comment by broodroosterdev** [comment]
Just tested it on my RPI, it works exactly as it is supposed to. It is ready to be merged! Please merge this pr before #3 and squash and merge instead of regular merge.

**Comment by broodroosterdev** [comment]
Also, please remove the github integration from docker hub before merging to avoid it giving problems

**Pull request merged**
